<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ $trip->title }} - WanderJournal Itinerary</title>
    <style>
        body {
            font-family: 'Times New Roman', Times, serif;
            color: #2C2A29;
            margin: 0;
            padding: 20px;
            background-color: #FDFBF7;
        }
        .header {
            text-align: center;
            border-bottom: 2px solid #8B4513;
            padding-bottom: 20px;
            margin-bottom: 30px;
        }
        .title {
            font-size: 32px;
            font-weight: bold;
            margin-bottom: 5px;
            color: #8B4513;
        }
        .subtitle {
            font-size: 16px;
            font-style: italic;
            color: #555;
        }
        .meta {
            margin-top: 10px;
            font-size: 14px;
            text-transform: uppercase;
            letter-spacing: 1px;
        }
        .day-block {
            margin-bottom: 40px;
            page-break-inside: avoid;
        }
        .day-header {
            background-color: #E8E1D5;
            padding: 10px 15px;
            font-weight: bold;
            font-size: 18px;
            border-left: 5px solid #8B4513;
            margin-bottom: 15px;
        }
        .item {
            margin-bottom: 15px;
            padding-left: 20px;
            border-left: 1px dashed #ccc;
        }
        .item-header {
            font-weight: bold;
            font-size: 16px;
        }
        .item-time {
            font-family: Arial, sans-serif;
            font-size: 12px;
            color: #D35400;
            margin-right: 10px;
            font-weight: bold;
        }
        .item-details {
            font-size: 14px;
            margin-top: 5px;
            line-height: 1.5;
        }
        .item-location {
            font-size: 12px;
            color: #5A6E4D;
            font-style: italic;
            margin-top: 3px;
        }
        .footer {
            margin-top: 50px;
            text-align: center;
            font-size: 12px;
            color: #888;
            border-top: 1px solid #ddd;
            padding-top: 20px;
        }
    </style>
</head>
<body>

    <div class="header">
        <div class="title">{{ $trip->title }}</div>
        <div class="subtitle">{{ $trip->destination->name }}, {{ $trip->destination->country }}</div>
        <div class="meta">
            {{ $trip->start_date->format('M d, Y') }} — {{ $trip->end_date->format('M d, Y') }} | {{ $trip->num_travelers }} Traveler(s)
        </div>
    </div>

    @foreach($trip->itineraryDays as $day)
        <div class="day-block">
            <div class="day-header">
                Day {{ $day->day_number }} - {{ $day->date ? $day->date->format('l, F j, Y') : '' }}
                @if($day->title)
                    : {{ $day->title }}
                @endif
            </div>

            @if($day->items->isEmpty())
                <div class="item">
                    <div class="item-details" style="font-style: italic; color: #888;">No planned activities for this day. Free time to explore!</div>
                </div>
            @endif

            @foreach($day->items as $item)
                <div class="item">
                    <div class="item-header">
                        @if($item->start_time)
                            <span class="item-time">{{ \Carbon\Carbon::parse($item->start_time)->format('h:i A') }}</span>
                        @endif
                        {{ $item->title }}
                    </div>
                    
                    @if($item->location)
                        <div class="item-location">Location: {{ $item->location }}</div>
                    @endif
                    
                    @if($item->description)
                        <div class="item-details">{{ $item->description }}</div>
                    @endif
                </div>
            @endforeach
        </div>
    @endforeach

    <div class="footer">
        Generated by WanderJournal Travel Planner<br>
        &copy; {{ date('Y') }} WanderJournal
    </div>

</body>
</html>
